# Generated by Django 5.2.4 on 2025-07-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ad_description_ad_location_alter_ad_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
