# Generated by Django 5.2.4 on 2025-07-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
