# Generated by Django 5.2.4 on 2025-07-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='Unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='model',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='vehicle_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
