# Generated by Django 5.2.4 on 2025-07-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_ad_fuel_type_ad_model_ad_vehicle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='ad',
            name='model',
            field=models.CharField(blank=True, default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='ad',
            name='vehicle_name',
            field=models.CharField(blank=True, default='Unknown', max_length=255),
        ),
    ]
