# Generated by Django 5.2.4 on 2025-07-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_ad_fuel_type_alter_ad_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='is_expired',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='views',
        ),
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('engine', 'Engine Parts'), ('lights', 'Lights & Electricals'), ('body', 'Body Parts'), ('interior', 'Interiors'), ('wheels', 'Wheels & Tyres'), ('brakes', 'Brakes'), ('suspension', 'Suspension'), ('exhaust', 'Exhaust'), ('transmission', 'Transmission')], default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='phone_number',
            field=models.CharField(default='Unknown', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='fuel_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(default='Uknown', upload_to='ads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ad',
            name='vehicle_name',
            field=models.CharField(max_length=100),
        ),
    ]
