# Generated by Django 5.2.4 on 2025-07-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_ad_is_active_remove_ad_is_expired_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='ad',
            name='mobile_number',
            field=models.CharField(default='Unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='fuel_type',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
