# Generated by Django 5.2.4 on 2025-07-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_ad_category_ad_is_active_ad_is_expired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='sub_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='transmission',
            field=models.CharField(blank=True, choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], default='Manual', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
