# Generated by Django 5.2.4 on 2025-07-31 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_ad_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='vehicle_name',
            new_name='make',
        ),
    ]
