# Generated by Django 5.2.4 on 2025-08-04 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
