# Generated by Django 5.2.4 on 2025-08-06 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_delete_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='created_at',
            new_name='added_on',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='core.ad'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'ad')},
        ),
    ]
