# Generated by Django 5.2.4 on 2025-08-11 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_userprofile_business_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='business_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='business_description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='business_email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='business_logo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='business_phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(blank=True, choices=[('retail', 'Retail'), ('service', 'Service'), ('manufacturing', 'Manufacturing'), ('other', 'Other')], max_length=50, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_logos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
