# Generated by Django 5.2.4 on 2025-08-16 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_userprofile_two_factor_enabled_securityactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(blank=True, choices=[('engine', 'Engine Parts'), ('lights', 'Lights & Electricals'), ('body', 'Body Parts'), ('interior', 'Interiors'), ('wheels', 'Wheels & Tyres'), ('brakes', 'Brakes'), ('suspension', 'Suspension'), ('exhaust', 'Exhaust'), ('transmission', 'Transmission')], null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
