# Generated by Django 5.2.4 on 2025-08-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_ad_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='make',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
