# Generated by Django 5.2.4 on 2025-08-19 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_ad_fuel_type_alter_ad_make_alter_ad_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_inquiries', models.BooleanField(default=True)),
                ('listing_performance', models.BooleanField(default=True)),
                ('payment_confirmations', models.BooleanField(default=True)),
                ('marketing_updates', models.BooleanField(default=False)),
                ('urgent_inquiries', models.BooleanField(default=True)),
                ('security_alerts', models.BooleanField(default=True)),
                ('real_time_chat', models.BooleanField(default=True)),
                ('call_requests', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
