# Generated by Django 5.2.4 on 2025-08-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_notificationpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='business_license',
            field=models.FileField(blank=True, null=True, upload_to='verification/business_licenses/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_license_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='govt_id',
            field=models.FileField(blank=True, null=True, upload_to='verification/govt_ids/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='govt_id_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
